# Generated by Django 5.1.3 on 2024-12-20 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='demo',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
