# Generated by Django 5.1.3 on 2025-01-05 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module1', '0003_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='record',
            name='text',
            field=models.TextField(),
        ),
    ]
