# Generated by Django 5.1.3 on 2025-01-05 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module1', '0004_alter_record_date_alter_record_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Samp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text1', models.CharField(max_length=50)),
                ('text2', models.CharField(max_length=50)),
            ],
        ),
    ]
